### ISSUE TITLE
joi module contains a moderate security vulnerability

### ISSUE THREAD

**Issue by adubatl** [icodeforlove/node-cloudflare#15]
Here is the hoek vulnerability
https://nodesecurity.io/advisories/566

![screen shot 2018-05-16 at 8 54 26 am](https://user-images.githubusercontent.com/17996250/40118061-cbe1e5a2-58e6-11e8-992e-aca84305fbe4.png)

New versions of joi do not have this vulnerability as they use hoek 5.x.x

**Comment by icodeforlove** [comment]
Ok, I'll look into updating this.

The usage of Joi here is purely just for dev usage, and shouldn't be directly exposed to the client in majority of use cases.

**Comment by adubatl** [comment]
Thank you :)

**Comment by icodeforlove** [comment]
updated
