### ISSUE TITLE
Update user rule by API

### ISSUE THREAD

**Issue by amirsalarpourhasan** [icodeforlove/node-cloudflare#9]
Hi
I1m using Nodejs + Expressjs and "cloudflare4" npm package. I just have a problem in updating user rule by API. this is my code:

cloudFApi.userFirewallAccessRuleUpdate('45cb36dcd7f79a59cc8607383c5748c0',{mode:"challenge", configuration:{value:"44.44.44.45",target:"ip"} , notes: "mode chalenged by node app"} , true).then(function (result) {
resp.send(result); 
}).catch(function(err){
resp.send(err); 
});

When I submitted this action, I`ll get nothing, no error, and no result. Other APIs action like adding CNAME are working correctly but updating user rule, response nothing!!! How can I fix it?

**Comment by icodeforlove** [comment]
Does the method ever complete? You can also try supplying a 3rd argument as true (raw). And it should give you the raw response directly from CF.

**Comment by amirsalarpourhasan** [comment]
I set the raw to true and false but both of them are not work!! 

This is my config:

`var cloudFApi = new CloudFlareAPI({ /* all settings are default settings */
  email: 'mail@email.com',
  key: 'key-11111111111111111111',
  itemsPerPage: 100, 
  maxRetries: 5, 
  raw: false , /* clacifying result */
  autoPagination: false, 
  autoPaginationConcurrency: 1 
});`

**Comment by amirsalarpourhasan** [comment]
please help me

**Comment by icodeforlove** [comment]
Not enough information
